### ISSUE TITLE
Permission to build on your work/license

### ISSUE THREAD

**Issue by nazdakka** [etowle/1822#32]
Hi,

Me and a couple of friends are designing our own 18xx game loosely based on 1822 (18OX). To carry on playtesting in the current mess, we're trying to go online and get things set up for online play using Board18. A spreadsheet is a requirement for that. Would it be OK if we forked your 1822 spreadsheet and adapted it to our game? We'd be very grateful and are happy to give credit to you for the original spreadsheet and link to your work for 1822 if we make 18OX public.

Thanks.

**Comment by etowle** [comment]
The spreadsheets linked here are modified from popular (public) 1822MX and 1822CA spreadsheets floating around the internet, so I can't claim credit for the bulk of their design. But I'm sure the original designers would be happy if you could use them for your own game. I recommend checking out the BOARD18 "dream spreadsheets" Google Drive folder, linked [here](https://wiki.board18.org/w/Dream_Spreadsheets).
