### ISSUE TITLE
CNoR capitalization issue

### ISSUE THREAD

**Issue by etowle** [etowle/1822#37]
There is an issue with the CNoR concession not being found if it is listed in a bid box during an SR. This is because CNoR is not capitalized in the game data, but we convert major names to all uppercase to compare them to the game data list.

**Comment by mjtsuk** [comment]
Hi, do you have a workaround? I'd like to use your scripts in a game starting Monday 6/8/2020. Thanks!

**Comment by etowle** [comment]
This should be fixed.

I made some structural changes to the sheet to make bidding (especially on privates) a bit smoother. I updated the script and ran some small tests, but I haven't played a full 1822MX/1822CA game to test it more robustly. If you run into any problems using the sheet/script, please open an issue. Thanks!

**Comment by mjtsuk** [comment]
Looks great. I will report back on any problems we find. Thanks for all your hard work!
