### ISSUE TITLE
Request locking previous tab when making new round

### ISSUE THREAD

**Issue by mjtsuk** [etowle/1822#39]
It would be nice if the new round script would lock the previous tab when making a new one. We've had lots of issues with players inadvertently entering things on old tabs. This code, added at line 1163 in 1822.gs, is working well for us.

curSheet.protect().setWarningOnly(true);

**Comment by etowle** [comment]
Great idea. I've entered data into the wrong sheet myself many times. Your code looks good, I'll add it now.

**Comment by mjtsuk** [comment]
It wasn't my code originally, Felix Rodriguez (Kaelistus on BGG) gave it to me.
By the way, what's your name? I'd like to praise you to the people I'm playing 1822CA with. :-)

**Comment by etowle** [comment]
Haha, my name is Eli Towle. I lurk around BGG occasionally, my username there is silverrainmaker.
