### ISSUE TITLE
Regional mail contracts don't pay corporations

### ISSUE THREAD

**Issue by ChrisTheCat** [etowle/1822#52]
The regional mail contracts pay $0 to corporations. They should pay 10/20/30/40.

**Comment by ChrisTheCat** [comment]
CK47 and CK48 need some kind of formula

**Comment by etowle** [comment]
Thanks for the issue. This is intentional. The "Mail Income" row is meant to cover both regional and national mail contracts. The mail income depends on the corporation operating a train, so we don't want to automatically give mail income to any corporation with a regional mail contract.

**Comment by ChrisTheCat** [comment]
Suggest adding a note to BM47 and BM48 to inform players of this.

**Comment by etowle** [comment]
Sure, done.
