### ISSUE TITLE
CNoR presidency put in wrong row

### ISSUE THREAD

**Issue by ChrisTheCat** [etowle/1822#53]
When the CNoR concession is purchased, the owner's name is entered in cell BF31 instead of BF32. This causes the script to object that it cannot find the concessions. Manually typing the owner's name in BF32 and typing "End Owner" in BF31 allows the script to run again.

**Comment by etowle** [comment]
Do you have a link to a sheet where this happens? I'm having trouble reproducing it.

**Comment by ChrisTheCat** [comment]
It happened on the transition from SR6 to OR6a in this sheet.

https://docs.google.com/spreadsheets/d/1Uo0hophTP0U5vtnjznCV2InmrMMWKHZ2CEK2AeFomlM/edit?usp=sharing

To fix it, we manually edited the cells.

**Comment by etowle** [comment]
I see, thanks.

**Comment by etowle** [comment]
This should now be fixed in the Google Sheet templates. Thanks for the report.
